name: GSI - Erfan

on: [push]

env:
  RECOVERY: https://drive.google.com/uc?id=1lawYvyhVstCS3Y4j03RA0VgBqTY-j-gx&export=download
  TZ: America/Sao_Paulo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Install the tools
         run: |
              git clone https://github.com/SebaUbuntu/TWRP-device-tree-generator setup
              cd setup
              chmod 0777 *
              sudo apt install cpio
              pip3 install .
              
       
       - name: Download recovery and extract tree
         run: |
              mkdir work
              cd work
              mkdir input
              wget $RECOVERY -P input
              python3 -m twrpdtgen input/*
              rm -r input
       
       - name: Upload tree
         run: |
              cd work/input/working
              zip -r tree.zip *
              touch link.txt
              ./transfer wet tree.zip | grep Download >> link.txt
       
       - name: Execute Shell Script
         run: |
               cat work/input/link.txt
