name: Tạo tree

on: [push]

env:
  RECOVERY: https://doc-0o-80-docs.googleusercontent.com/docs/securesc/if29ailm9asubceum7d4i81u0va33rs4/cgh7q67fp17pmromrk0babmro1a8eahb/1616552850000/06241952564137785350/06241952564137785350/1xegoVNFGnvbXNbD3_RG59-mOjGth4x86?e=download&authuser=0&nonce=b57ak6kknp78c&user=06241952564137785350&hash=l9iv06dv46qb8j38qpeal8dni07q7kqm
  TZ: America/Sao_Paulo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Install the tools
         run: |
              git clone https://github.com/SebaUbuntu/TWRP-device-tree-generator setup
              cd setup
              chmod 0777 *
              sudo apt install cpio
              pip3 install .
              
       
       - name: Download recovery and extract tree
         run: |
              mkdir work
              cd work
              mkdir input
              wget $RECOVERY -P input
              python3 -m twrpdtgen --output OUTPUT --no-git recovery_image input/*
              rm -r input
       
       - name: Upload tree
         run: |
              cd work/input
              zip -r tree.zip *
              touch link.txt
              ./transfer wet tree.zip | grep Download >> link.txt
       
       - name: Execute Shell Script
         run: |
               cat work/input/link.txt
