name: Tạo tree

on: [push]

env:
  RECOVERY: https://download938.mediafire.com/08zucy9htwmg/66bl6fiut9bxfvi/recovery.img
  TZ: America/Sao_Paulo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Install the tools
         run: |
              git clone https://github.com/SebaUbuntu/TWRP-device-tree-generator
              cd TWRP-device-tree-generator
              chmod 0777 *
              sudo apt install cpio
              sudo pacman -S cpio
              sudo -E apt-get -qq install git openjdk-8-jdk wget
              pip3 install .
              
       
       - name: Download recovery and extract tree
         run: |
              mkdir work
              cd work
              wget $RECOVERY
              python3 -m twrpdtgen --output OUTPUT --no-git recovery_image
       
       - name: Upload tree
         run: |
              cd work
              zip -r tree.zip *
              touch link.txt
              ./transfer wet tree.zip | grep Download >> link.txt
       
       - name: Execute Shell Script
         run: |
               cat work/input/link.txt
